-- Tabela usada pelos nós "Encontrar Cliente" e "Criar Cliente"
create table if not exists public."Leads" (
  id          bigint generated by default as identity primary key,
  lead_id     text not null unique, -- número do WhatsApp (remoteJid sem o @s.whatsapp.net)
  lead_nome   text,                 -- nome do perfil no WhatsApp (pushName)
  created_at  timestamptz not null default now()
);
